# # version: '3.8'
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     ports:
#       - "5170:5170"
#     volumes:
#       - ./backend:/app
#     environment:
#       - NODE_ENV=development

#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile.frontend
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./frontend:/app
#     environment:
#       - NODE_ENV=development